AllCops:
  TargetRubyVersion: 3.0.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
