AllCops:
  TargetRubyVersion: 3.0.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'config/initializers/**'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20220221104139_create_active_storage_tables.active_storage.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/20220221104139_create_active_storage_tables.active_storage.rb'
